/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Base {
  Base._();

  static const _kFontFam = 'Base';

  static const IconData sousuo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData lishi = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData sousuo1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lishi1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData dingyue = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fankui = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData fankuixuanzhong = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData guanyu = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData guanyuxuanzhong = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heji = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData huati = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData huatixuanzhong = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData leibie = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData leibiexuanzhong = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData mianze = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData mianzexuanzhong = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData qingdan = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData qingdanxuanzhong = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData shezhi = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData shezhixuanzhong = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData zujixuanzhong = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData zuji = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData wodexuanzhong = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData wode = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData shouyexuanzhong = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData shouye = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData shoujihaoxuanzhong = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData shoujihao = const IconData(0xe81b, fontFamily: _kFontFam);
}
